-- Run after assets.sql and add_currency_columns.sql in the Supabase SQL editor.
begin;
create table if not exists public.payment_names (
  id bigint generated by default as identity primary key,
  name text not null check (length(btrim(regexp_replace(name, '[[:space:]]+', ' ', 'g'))) between 1 and 200),
  is_active boolean not null default true
);
create unique index if not exists payment_names_normalized_name_idx
  on public.payment_names (lower(btrim(regexp_replace(name, '[[:space:]]+', ' ', 'g'))));
create table if not exists public.payment_plans (
  id uuid primary key,
  name text not null check (length(trim(name)) between 1 and 200),
  category_id bigint not null references public.categories(id),
  currency text not null check (currency in ('MYR', 'SGD')),
  created_at timestamptz not null default now()
);
alter table public.payment_plans add column if not exists payment_name_id bigint
  references public.payment_names(id) on delete restrict;
-- Backfill old free-text names without reactivating archived options on reruns.
with legacy_names as (
  select coalesce(nullif(btrim(regexp_replace(name, '[[:space:]]+', ' ', 'g')), ''), 'Unnamed payment') as name,
    created_at, id
  from public.payment_plans where payment_name_id is null
)
insert into public.payment_names(name)
select distinct on (lower(name)) name from legacy_names order by lower(name), created_at, id
on conflict do nothing;
update public.payment_plans p set payment_name_id = n.id, name = n.name
from public.payment_names n
where p.payment_name_id is null
  and lower(coalesce(nullif(btrim(regexp_replace(p.name, '[[:space:]]+', ' ', 'g')), ''), 'Unnamed payment'))
    = lower(btrim(regexp_replace(n.name, '[[:space:]]+', ' ', 'g')));
alter table public.payment_plans alter column payment_name_id set not null;
create index if not exists payment_plans_payment_name_idx on public.payment_plans(payment_name_id);
create table if not exists public.payment_installments (
  id bigint generated by default as identity primary key,
  plan_id uuid not null references public.payment_plans(id),
  sequence integer not null,
  amount numeric(12,2) not null check (amount > 0),
  due_date date not null,
  status text not null default 'scheduled' check (status in ('scheduled','posted','cancelled','reversed')),
  asset_id integer references public.assets(id) on delete restrict,
  unique(plan_id, sequence)
);
alter table public.expenses add column if not exists payment_installment_id bigint
  references public.payment_installments(id) on delete restrict;
create unique index if not exists expenses_payment_installment_idx on public.expenses(payment_installment_id);
create index if not exists payment_installments_due_idx on public.payment_installments(due_date) where status = 'scheduled';
alter table public.payment_plans enable row level security;
alter table public.payment_installments enable row level security;
alter table public.payment_names enable row level security;
-- Matches this application's existing shared, unauthenticated ledger model.
drop policy if exists payment_names_access on public.payment_names;
create policy payment_names_access on public.payment_names for all using (true) with check (true);
drop policy if exists payment_plans_access on public.payment_plans;
create policy payment_plans_access on public.payment_plans for all using (true) with check (true);
drop policy if exists payment_installments_access on public.payment_installments;
create policy payment_installments_access on public.payment_installments for all using (true) with check (true);
grant select, insert, update on public.payment_names, public.payment_plans, public.payment_installments to anon, authenticated;
grant usage, select on sequence public.payment_names_id_seq, public.payment_installments_id_seq to anon, authenticated;

create or replace function public.save_payment_name(p_name text, p_id bigint default null)
returns bigint language plpgsql set search_path = public as $$
declare clean_name text; existing_id bigint; saved_id bigint;
begin
  perform pg_advisory_xact_lock(726194201);
  clean_name := btrim(regexp_replace(p_name, '[[:space:]]+', ' ', 'g'));
  if clean_name is null or length(clean_name) not between 1 and 200 then
    raise exception 'Enter a payment name between 1 and 200 characters';
  end if;
  select id into existing_id from public.payment_names
    where lower(btrim(regexp_replace(name, '[[:space:]]+', ' ', 'g'))) = lower(clean_name);
  if p_id is null then
    if existing_id is not null then
      update public.payment_names set is_active = true where id = existing_id;
      return existing_id;
    end if;
    insert into public.payment_names(name) values(clean_name) returning id into saved_id;
    return saved_id;
  end if;
  if not exists(select 1 from public.payment_names where id = p_id) then
    raise exception 'Payment name not found';
  end if;
  if existing_id is not null and existing_id <> p_id then
    raise exception 'A payment name with this name already exists. Select the existing name instead';
  end if;
  update public.payment_names set name = clean_name where id = p_id;
  -- Keep historical expenses as recorded; current plan labels follow the name.
  update public.payment_plans set name = clean_name where payment_name_id = p_id;
  return p_id;
end $$;

create or replace function public.remove_payment_name(p_id bigint)
returns void language plpgsql set search_path = public as $$
begin
  perform pg_advisory_xact_lock(726194201);
  update public.payment_names set is_active = false where id = p_id;
  if not found then raise exception 'Payment name not found'; end if;
end $$;

create or replace function public.adjust_main_asset_balance(p_currency text, p_delta numeric)
returns void language sql set search_path = public as $$
  update public.assets set current_value = current_value + p_delta, updated_at = now()
  where is_main and currency = p_currency;
$$;

-- Every linked expense mutation adjusts the ORIGINAL asset atomically.
create or replace function public.sync_payment_expense() returns trigger
language plpgsql set search_path = public as $$
declare item public.payment_installments; plan public.payment_plans; target integer;
begin
  if TG_OP = 'UPDATE' and new.payment_installment_id is distinct from old.payment_installment_id then
    raise exception 'Cannot change the payment plan link';
  end if;
  if TG_OP = 'DELETE' then
    if old.payment_installment_id is null then return old; end if;
    select * into item from public.payment_installments where id = old.payment_installment_id for update;
    update public.assets set current_value = current_value + old.amount, updated_at = now() where id = item.asset_id;
    update public.payment_installments set status = 'reversed' where id = item.id;
    return old;
  end if;
  if new.payment_installment_id is null then return new; end if;
  select * into item from public.payment_installments where id = new.payment_installment_id for update;
  select * into strict plan from public.payment_plans where id = item.plan_id;
  if new.currency is distinct from plan.currency or new.amount <= 0 then
    raise exception 'Plan expenses must keep their currency and a positive amount';
  end if;
  if TG_OP = 'INSERT' then
    if item.status <> 'scheduled' or item.due_date > (now() at time zone 'Asia/Kuala_Lumpur')::date then
      raise exception 'Installment is not due';
    end if;
    select id into target from public.assets where is_main and currency = plan.currency for update;
    if target is null then raise exception 'Set a main asset for % before posting payments', plan.currency; end if;
    update public.assets set current_value = current_value - new.amount, updated_at = now() where id = target;
    update public.payment_installments set status = 'posted', asset_id = target, amount = new.amount where id = item.id;
  else
    update public.assets set current_value = current_value + old.amount - new.amount, updated_at = now() where id = item.asset_id;
    update public.payment_installments set amount = new.amount where id = item.id;
  end if;
  return new;
end $$;
drop trigger if exists payment_expense_sync on public.expenses;
create trigger payment_expense_sync before insert or update or delete on public.expenses
for each row execute function public.sync_payment_expense();

create or replace function public.process_due_payment_installments() returns integer
language plpgsql set search_path = public as $$
declare item record; processed integer := 0;
begin
  -- Serialize concurrent cron/browser runs; expense uniqueness is a second safeguard.
  perform pg_advisory_xact_lock(726194201);
  for item in
    select i.*, p.name, p.category_id, p.currency
    from public.payment_installments i join public.payment_plans p on p.id = i.plan_id
    where i.status = 'scheduled' and i.due_date <= (now() at time zone 'Asia/Kuala_Lumpur')::date
      and exists (select 1 from public.assets a where a.is_main and a.currency = p.currency)
    order by i.due_date, i.id for update of i
  loop
    insert into public.expenses(amount, currency, note, expense_date, category_id, payment_installment_id)
    values(item.amount, item.currency, item.name || ' - Payment ' || item.sequence, item.due_date, item.category_id, item.id);
    processed := processed + 1;
  end loop;
  return processed;
end $$;

-- Replace old signatures to avoid ambiguous API overloads. Defaults preserve old clients.
drop function if exists public.create_payment_plan(uuid, text, bigint, text, numeric, integer, date);
drop function if exists public.create_payment_plan(uuid, text, bigint, text, numeric, integer, date, numeric[]);
create or replace function public.create_payment_plan(
  p_id uuid, p_name text, p_category_id bigint, p_currency text,
  p_total numeric, p_count integer, p_first_date date, p_amounts numeric[] default null,
  p_payment_name_id bigint default null
) returns uuid language plpgsql set search_path = public as $$
declare cents bigint; base bigint; idx integer; month_start date; due date;
  chosen_name public.payment_names;
begin
  perform pg_advisory_xact_lock(726194201);
  if exists(select 1 from public.payment_plans where id = p_id) then return p_id; end if;
  if p_total is null or p_total <= 0 or p_total > 9999999999.99 or round(p_total, 2) <> p_total
    or p_count is null or p_count not between 1 and 360 or p_first_date is null
    or p_first_date not between date '1900-01-01' and date '2200-01-01' then
    raise exception 'Invalid amount, installment count or date';
  end if;
  cents := p_total * 100;
  if cents < p_count then raise exception 'Each installment must be at least 0.01'; end if;
  if p_amounts is not null then
    if cardinality(p_amounts) <> p_count or array_ndims(p_amounts) <> 1 or array_lower(p_amounts, 1) <> 1
      or exists(select 1 from unnest(p_amounts) amount where amount is null or amount <= 0 or amount > 9999999999.99 or round(amount,2) <> amount)
      or (select sum(amount) from unnest(p_amounts) amount) <> p_total then
      raise exception 'Payment amounts must be positive, have at most two decimal places and add up to the total payable';
    end if;
  end if;
  if not exists(select 1 from public.assets where is_main and currency = p_currency) then
    raise exception 'Set a main asset for % before creating a plan', p_currency;
  end if;
  if p_payment_name_id is null then
    p_payment_name_id := public.save_payment_name(p_name);
  end if;
  select * into chosen_name from public.payment_names where id = p_payment_name_id and is_active;
  if not found then raise exception 'Select an active payment name'; end if;
  base := cents / p_count;
  insert into public.payment_plans(id,name,payment_name_id,category_id,currency)
    values(p_id,chosen_name.name,chosen_name.id,p_category_id,p_currency);
  for idx in 0..p_count-1 loop
    month_start := (date_trunc('month', p_first_date) + make_interval(months => idx))::date;
    due := month_start + (least(extract(day from p_first_date)::integer,
      extract(day from month_start + interval '1 month - 1 day')::integer) - 1);
    insert into public.payment_installments(plan_id,sequence,amount,due_date)
    values(p_id,idx+1,coalesce(p_amounts[idx+1],(case when idx = p_count-1 then cents-base*(p_count-1) else base end)::numeric/100),due);
  end loop;
  perform public.process_due_payment_installments();
  return p_id;
end $$;

create or replace function public.change_payment_installment(p_id bigint, p_cancel boolean, p_amount numeric, p_date date)
returns void language plpgsql set search_path = public as $$
declare item public.payment_installments;
begin
  perform pg_advisory_xact_lock(726194201);
  select * into strict item from public.payment_installments where id = p_id for update;
  if item.status <> 'scheduled' then raise exception 'Only scheduled installments can be changed'; end if;
  if p_cancel then
    update public.payment_installments set status = 'cancelled' where id = p_id;
  else
    if p_amount is null or p_amount <= 0 or round(p_amount,2) <> p_amount or p_date is null then
      raise exception 'Enter a positive amount and valid date';
    end if;
    update public.payment_installments set amount = p_amount, due_date = p_date where id = p_id;
    perform public.process_due_payment_installments();
  end if;
end $$;
commit;
notify pgrst, 'reload schema';
