create table if not exists public.recurring_expenses (
  id bigint generated by default as identity primary key
);

alter table public.recurring_expenses
add column if not exists name text;

alter table public.recurring_expenses
add column if not exists amount numeric(12, 2);

alter table public.recurring_expenses
add column if not exists description text;

alter table public.recurring_expenses
add column if not exists category_id bigint;

alter table public.recurring_expenses
add column if not exists repeat_day integer default 1;

alter table public.recurring_expenses
add column if not exists is_active boolean default true;

alter table public.recurring_expenses
add column if not exists created_at timestamptz default timezone('utc'::text, now());

alter table public.recurring_expenses
add column if not exists updated_at timestamptz default timezone('utc'::text, now());

update public.recurring_expenses
set name = 'Recurring expense'
where name is null;

update public.recurring_expenses
set amount = 0.01
where amount is null;

update public.recurring_expenses
set repeat_day = 1
where repeat_day is null;

update public.recurring_expenses
set is_active = true
where is_active is null;

update public.recurring_expenses
set created_at = timezone('utc'::text, now())
where created_at is null;

update public.recurring_expenses
set updated_at = timezone('utc'::text, now())
where updated_at is null;

update public.recurring_expenses
set category_id = (
  select id
  from public.categories
  order by id
  limit 1
)
where category_id is null;

alter table public.recurring_expenses
alter column name set not null,
alter column amount set not null,
alter column repeat_day set not null,
alter column is_active set not null,
alter column created_at set not null,
alter column updated_at set not null;

do $$
begin
  if exists (
    select 1
    from public.recurring_expenses
    where category_id is null
  ) then
    raise exception 'Please create at least one category before setting up recurring expenses.';
  end if;
end $$;

alter table public.recurring_expenses
alter column category_id set not null;

alter table if exists public.expenses
add column if not exists recurring_expense_id bigint;

alter table if exists public.expenses
add constraint if not exists expenses_recurring_expense_id_fkey
foreign key (recurring_expense_id)
references public.recurring_expenses(id)
on update cascade
on delete set null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'recurring_expenses_amount_positive'
      and conrelid = 'public.recurring_expenses'::regclass
  ) then
    alter table public.recurring_expenses
    add constraint recurring_expenses_amount_positive
    check (amount > 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'recurring_expenses_repeat_day_range'
      and conrelid = 'public.recurring_expenses'::regclass
  ) then
    alter table public.recurring_expenses
    add constraint recurring_expenses_repeat_day_range
    check (repeat_day between 1 and 31);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'recurring_expenses_category_id_fkey'
      and conrelid = 'public.recurring_expenses'::regclass
  ) then
    alter table public.recurring_expenses
    add constraint recurring_expenses_category_id_fkey
    foreign key (category_id)
    references public.categories(id)
    on update cascade
    on delete restrict;
  end if;
end $$;

create or replace function public.set_recurring_expenses_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists recurring_expenses_updated_at on public.recurring_expenses;

create trigger recurring_expenses_updated_at
before update on public.recurring_expenses
for each row
execute function public.set_recurring_expenses_updated_at();

alter table public.recurring_expenses enable row level security;

drop policy if exists "Allow anon access to recurring expenses"
on public.recurring_expenses;

create policy "Allow anon access to recurring expenses"
on public.recurring_expenses
for all
using (true)
with check (true);

notify pgrst, 'reload schema';
