"use client";
import { useState } from "react";
import type { LifeScenario } from "../types/lifeScenario";
import type { FutureExpenseLibrary } from "../types/futureExpense";
import type { analyzeScenario } from "../utils/lifeScenario";
import { expensePlanSummary, ordered } from "../utils/futureExpense";
import { Card } from "./ui/Card";
import { Select } from "./ui/Field";

export default function FutureExpenseAnalysis({ scenario: s, library, result: r }: { scenario: LifeScenario; library: FutureExpenseLibrary; result: NonNullable<ReturnType<typeof analyzeScenario>> }) {
  const [month, setMonth] = useState("");
  const row = r.rows.find(row => row.month === month) || r.rows[Math.min(1, r.rows.length - 1)];
  const f = (n: number) => `${s.currency} ${n.toLocaleString("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const plan = library.plans.find(p => p.id === s.expense_plan_id)!;
  const summary = expensePlanSummary(plan, library, s.currency, s.fx);
  return <>
    <Card><h2 className="text-xl font-semibold">Your planned cost of living</h2><p className="mt-1 text-sm text-slate-500">{plan.name} · Default plan outside named phases. Each phase can use a different plan.</p><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-3">{[["Monthly Living Cost", r.monthlyLiving], ["Average Projected Monthly Spending", r.averageSpending], ["Total Projected Spending", r.totalSpending], ["Total Fixed Commitments", r.totalFixed], ["Total One-Time Costs", r.totalOneTime]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold">{f(Number(value))}</p></div>)}</div><p className="mt-3 text-xs text-slate-500">The base monthly living cost excludes temporary instalments and one-time events. Projected averages include partial months, phase changes, active item dates and inflation. Fixed commitments include fixed living items and temporary liabilities.</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{ordered(library.types).filter(t => summary.byType[t.id] !== undefined).map(t => <details key={t.id} className="rounded-lg border border-slate-200 p-3 dark:border-slate-700"><summary className="cursor-pointer text-sm">{t.name} · {f(summary.byType[t.id])} · {summary.total > 0 ? (summary.byType[t.id] / summary.total * 100).toFixed(1) : 0}%</summary><p className="mt-2 text-xs text-slate-500">Behavior: {t.behavior_tag}</p><ul className="mt-2 space-y-1 text-sm">{ordered(library.categories.filter(c => c.type_id === t.id)).map(c => <li key={c.id}>{c.name} · {f(summary.byCategory[c.id] || 0)}</li>)}</ul></details>)}</div></Card>
    <Card><h2 className="font-semibold">Future month preview</h2><label className="mt-3 block text-sm">Preview month<Select value={row.month} onChange={e => setMonth(e.target.value)}>{r.rows.map(row => <option key={row.month}>{row.month}</option>)}</Select></label><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Living cost", row.living_cost], ["Temporary instalments", row.liability_payments], ["One-time costs", row.one_time_events], ["Expected spending", row.total_outflow]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{f(Number(value))}</p></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm">What makes up this month?</summary><div className="mt-2 space-y-2 text-sm">{ordered(library.types).filter(t => row.by_type[t.id] !== undefined).map(t => <details key={t.id}><summary className="cursor-pointer">{t.name} · {f(row.by_type[t.id])}</summary><ul className="pl-4">{ordered(library.categories.filter(c => c.type_id === t.id && row.by_category[c.id] !== undefined)).map(c => <li key={c.id}>{c.name} · {f(row.by_category[c.id])}</li>)}</ul></details>)}</div></details><details className="mt-4"><summary className="cursor-pointer text-sm">Expense calendar across all months</summary><div className="mt-3 overflow-x-auto"><table className="w-full whitespace-nowrap text-right text-sm"><thead><tr><th className="p-2 text-left">Month</th><th className="p-2">Living cost</th><th className="p-2">Temporary commitments</th><th className="p-2">One-time costs</th><th className="p-2">Expected spending</th></tr></thead><tbody>{r.rows.map(row => <tr key={row.month} className="border-t border-slate-200 dark:border-slate-700"><th className="p-2 text-left">{row.month}</th><td className="p-2">{f(row.living_cost)}</td><td className="p-2">{f(row.liability_payments)}</td><td className="p-2">{f(row.one_time_events)}</td><td className="p-2 font-medium">{f(row.total_outflow)}</td></tr>)}</tbody></table></div></details></Card>
    {!!r.phases.length && <Card><h2 className="font-semibold">Total cost of each life phase</h2><p className="mt-1 text-xs text-slate-500">Exact phase dates determine partial-month costs. Phase net cashflow is income minus spending, before month-end expected yield.</p><div className="mt-4 grid gap-3 xl:grid-cols-2">{r.phases.map(p => <section key={p.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><h3 className="font-semibold">{p.name}</h3><p className="mt-1 text-xs text-slate-500">{p.days} days · {p.planName}</p><dl className="mt-3 space-y-2 text-sm">{[["Monthly living cost", p.monthlyLiving], ["Living expenses during phase", p.living], ["Temporary commitments", p.liabilities], ["One-time costs", p.oneTime], ["Total phase spending", p.total], ["Income", p.income], ["Net cashflow", p.net]].map(([label, value]) => <div key={label} className="flex justify-between gap-3"><dt>{label}</dt><dd className="font-medium tabular-nums">{f(Number(value))}</dd></div>)}</dl></section>)}</div></Card>}
  </>;
}
