"use client";
import { useState } from "react";
import type { Currency } from "../types/currency";
import type { ScenarioExpense } from "../types/lifeScenario";
import type { FutureExpenseItem, FutureExpenseLibrary, FutureExpensePlan } from "../types/futureExpense";
import { amountIn, duplicateExpensePlan, expensePlanSummary, importExpenseSuggestions, itemBehavior, itemIsEnabled, newExpenseItem, newExpensePlan, ordered, validateExpensePlan } from "../utils/futureExpense";
import { uid } from "../utils/scenarioMath";
import { Button } from "./ui/Button";
import { Input, Select, Textarea } from "./ui/Field";
import FutureExpenseHierarchy from "./FutureExpenseHierarchy";

interface Props {
  library: FutureExpenseLibrary;
  onChange: (library: FutureExpenseLibrary) => void;
  currency: Currency;
  fx: Record<Currency, number>;
  suggestions: ScenarioExpense[];
  selectedPlanId: string;
  onSelectPlan: (id: string) => void;
  usage?: Record<string, number>;
}
const format = (amount: number, currency: Currency) => `${currency} ${amount.toLocaleString("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function FutureExpensePlanEditor({ library, onChange, currency, fx, suggestions, selectedPlanId, onSelectPlan, usage = {} }: Props) {
  const [error, setError] = useState("");
  const [editingItem, setEditingItem] = useState<string | null>(null);
  const [filters, setFilters] = useState({ type: "", category: "", source: "", enabled: "all" });
  const [factor, setFactor] = useState(1);
  const [copyName, setCopyName] = useState("");
  const plan = library.plans.find(p => p.id === selectedPlanId);
  const summary = plan ? expensePlanSummary(plan, library, currency, fx) : null;
  const errors = plan ? validateExpensePlan(plan, library) : [];
  const save = (next: FutureExpenseLibrary) => { onChange(next); setError(""); };
  const attempt = (action: () => void) => { try { action(); } catch (e) { setError((e as Error).message); } };
  const changePlan = (next: FutureExpensePlan, rememberMapping?: FutureExpenseItem) => {
    let mappings = library.mappings;
    if (rememberMapping?.source_category_id && rememberMapping.type_id && rememberMapping.category_id) mappings = [...mappings.filter(m => m.source_category_id !== rememberMapping.source_category_id), { source_category_id: rememberMapping.source_category_id, future_type_id: rememberMapping.type_id, future_category_id: rememberMapping.category_id }];
    save({ ...library, mappings, plans: library.plans.map(p => p.id === next.id ? next : p) });
  };
  function updateItem(item: FutureExpenseItem, patch: Partial<FutureExpenseItem>, remember = false) {
    if (!plan) return;
    const next = { ...item, ...patch, updated_at: new Date().toISOString() };
    attempt(() => changePlan({ ...plan, confirmed: false, updated_at: next.updated_at, items: plan.items.map(i => i.id === item.id ? next : i) }, remember ? next : undefined));
  }
  const visible = plan?.items.filter(item => (!filters.type || item.type_id === filters.type) && (!filters.category || item.category_id === filters.category) && (!filters.source || item.source_type === filters.source) && (filters.enabled === "all" || (filters.enabled === "enabled" ? itemIsEnabled(item, library) : !itemIsEnabled(item, library)))) || [];
  const renderItem = (item: FutureExpenseItem) => {
    const active = itemIsEnabled(item, library);
    const converted = amountIn(item, currency, fx);
    const historical = item.historical_average === undefined ? null : amountIn({ ...item, amount: item.historical_average, currency: item.historical_currency || item.currency }, currency, fx);
    const difference = converted !== null && historical !== null ? converted - historical : null;
    return <article key={item.id} aria-label={`Expense ${item.name}`} className="rounded-xl border border-slate-200 p-3 dark:border-slate-700">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{item.name} {!active && <span className="text-xs text-slate-500">· Excluded</span>}</p><p className="mt-1 text-sm">{format(item.amount, item.currency)} / month</p><p className="text-xs text-slate-500">{item.source_type.replaceAll("_", " ")} · {itemBehavior(item, library)}{item.is_fixed ? " · Fixed amount" : ""}{item.source_reference_id ? ` · ${item.source_reference_id}` : ""}</p>{item.start_date || item.end_date ? <p className="text-xs text-slate-500">Active {item.start_date || "from scenario start"} to {item.end_date || "scenario end"}</p> : null}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => setEditingItem(editingItem === item.id ? null : item.id)}>Edit expense</Button><Button size="sm" variant="secondary" onClick={() => updateItem(item, { enabled: !item.enabled })}>{item.enabled ? "Disable expense" : "Enable expense"}</Button><Button size="sm" variant="secondary" onClick={() => attempt(() => { const now = new Date().toISOString(); const copy = { ...item, id: uid(), name: `${item.name} (Copy)`, source_type: "USER_CREATED" as const, source_reference_id: undefined, source_category_id: undefined, created_at: now, updated_at: now }; changePlan({ ...plan!, confirmed: false, items: [...plan!.items, copy] }); setEditingItem(copy.id); })}>Duplicate expense</Button><Button size="sm" variant="secondary" onClick={() => { if (window.confirm(`Delete “${item.name}” from this reusable plan? Phase overrides for this item will be removed. Actual records are unchanged.`)) attempt(() => changePlan({ ...plan!, confirmed: false, items: plan!.items.filter(i => i.id !== item.id) })); }}>Delete expense</Button></div></div>
      {historical !== null && <p className="mt-2 rounded-lg bg-slate-50 p-2 text-xs text-slate-500 dark:bg-slate-800">Historical average {format(historical, currency)} · Planned {converted === null ? "Set FX" : format(converted, currency)}{difference !== null ? ` · Difference ${difference >= 0 ? "+" : ""}${format(difference, currency)}${historical > 0 ? ` / ${(difference / historical * 100).toFixed(1)}%` : ""}` : ""}</p>}
      {editingItem === item.id && <div className="mt-4 grid gap-3 border-t border-slate-200 pt-4 dark:border-slate-700 sm:grid-cols-2">
        <label className="text-sm">Expense name<Input value={item.name} onChange={e => updateItem(item, { name: e.target.value })} /></label><label className="text-sm">Planned monthly amount<Input type="number" min={0} step="0.01" value={item.amount} onChange={e => updateItem(item, { amount: Number(e.target.value), source_type: "USER_OVERRIDE" })} /></label>
        <label className="text-sm">Expense currency<Select value={item.currency} onChange={e => updateItem(item, { currency: e.target.value as Currency, source_type: "USER_OVERRIDE" })}><option>MYR</option><option>SGD</option></Select></label>
        <label className="text-sm">Expense type<Select value={item.type_id || ""} onChange={e => updateItem(item, { type_id: e.target.value || null, category_id: null })}><option value="">Unmapped — choose type</option>{ordered(library.types).map(t => <option key={t.id} value={t.id}>{t.name || "Unnamed type"}{t.is_active ? "" : " (disabled)"}</option>)}</Select></label>
        <label className="text-sm">Expense category<Select disabled={!item.type_id} value={item.category_id || ""} onChange={e => updateItem(item, { category_id: e.target.value || null }, true)}><option value="">Unmapped — choose category</option>{ordered(library.categories.filter(c => c.type_id === item.type_id)).map(c => <option key={c.id} value={c.id}>{c.name || "Unnamed category"}{c.is_active ? "" : " (disabled)"}</option>)}</Select></label>
        <label className="text-sm">Payment day (blank = prorated monthly)<Input type="number" min={1} max={31} value={item.repeat_day ?? ""} onChange={e => updateItem(item, { repeat_day: e.target.value ? Number(e.target.value) : undefined, source_type: "USER_OVERRIDE" })} /></label>
        <label className="text-sm">Expense start date (optional)<Input type="date" value={item.start_date || ""} onChange={e => updateItem(item, { start_date: e.target.value || undefined })} /></label><label className="text-sm">Expense end date (optional)<Input type="date" value={item.end_date || ""} onChange={e => updateItem(item, { end_date: e.target.value || undefined })} /></label>
        <label className="flex gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={item.is_fixed} onChange={e => updateItem(item, { is_fixed: e.target.checked })} />Fixed amount — exclude from inflation and percentage-based plan generation</label>
        <label className="text-sm sm:col-span-2">Expense note<Textarea value={item.note} onChange={e => updateItem(item, { note: e.target.value })} /></label>{item.source_category_id && <p className="text-xs text-slate-500 sm:col-span-2">Category selection is remembered for future imports from historical category {item.source_category_id}.</p>}
        <Button size="sm" variant="secondary" onClick={() => setEditingItem(null)}>Done editing expense</Button>
      </div>}
    </article>;
  };
  return <div className="space-y-4">
    <div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-sm">Future expense plan<Select value={selectedPlanId} onChange={e => { onSelectPlan(e.target.value); setEditingItem(null); }}><option value="">Select an explicit monthly living plan</option>{library.plans.map(p => <option key={p.id} value={p.id}>{p.name} · {p.currency} · {p.confirmed ? "Confirmed" : "Draft"}</option>)}</Select></label><Button variant="secondary" onClick={() => attempt(() => { const next = newExpensePlan(currency); save({ ...library, plans: [...library.plans, next] }); onSelectPlan(next.id); setEditingItem(null); })}>Create expense plan</Button></div>
    <p className="text-xs text-slate-500">Reusable plan and hierarchy edits save immediately on this device. Financial changes require plan confirmation again. Scenario assignments and phase overrides use the scenario Save button.</p>
    {error && <p role="alert" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{error}</p>}
    {plan && summary && <>
      <div className="rounded-xl bg-teal-50 p-4 dark:bg-teal-950"><p className="text-sm font-medium">Expected Monthly Spending</p><p className="mt-1 text-3xl font-semibold" data-testid="monthly-plan-total">{summary.missingFx ? "Set FX for all enabled items" : format(summary.total, currency)}</p><p className="mt-2 text-xs text-slate-500">Base monthly living cost from enabled items and active types/categories. Item dates, instalments, one-time costs and inflation are applied separately in the month preview.</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{ordered(library.types).map(t => <details key={t.id} className="rounded-lg bg-white p-3 dark:bg-slate-900"><summary className="cursor-pointer text-sm">{t.name} · {format(summary.byType[t.id] || 0, currency)} · {summary.total > 0 ? ((summary.byType[t.id] || 0) / summary.total * 100).toFixed(1) : "0"}%</summary><ul className="mt-2 space-y-1 text-xs">{ordered(library.categories.filter(c => c.type_id === t.id)).map(c => <li key={c.id}>{c.name} · {format(summary.byCategory[c.id] || 0, currency)}</li>)}</ul><p className="mt-2 text-xs text-slate-500">Behavior: {t.behavior_tag}{!t.is_active ? " · Disabled" : ""}</p></details>)}</div></div>
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Expense plan name<Input value={plan.name} onChange={e => attempt(() => changePlan({ ...plan, name: e.target.value, confirmed: false, updated_at: new Date().toISOString() }))} /></label><label className="text-sm">Plan description<Input value={plan.description} onChange={e => attempt(() => changePlan({ ...plan, description: e.target.value, updated_at: new Date().toISOString() }))} /></label></div>
      <label className="block max-w-xs text-sm">Plan default currency<Select value={plan.currency} onChange={e => attempt(() => changePlan({ ...plan, currency: e.target.value as Currency, confirmed: false }))}><option>MYR</option><option>SGD</option></Select></label>
      <p className="text-xs text-slate-500">Existing item currencies are retained. New items use the plan default; totals are shown in {currency} using the scenario FX assumptions.</p>
      <p className="text-xs text-slate-500">Used by {usage[plan.id] || 0} saved scenarios. To experiment without changing their shared plan, duplicate this plan first.</p>
      <div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => attempt(() => { const item = newExpenseItem(plan); changePlan({ ...plan, confirmed: false, items: [...plan.items, item] }); setEditingItem(item.id); setFilters({ type: "", category: "", source: "", enabled: "all" }); })}>Add Expense</Button><Button variant="secondary" disabled={!suggestions.some(x => x.source_type === "HISTORICAL")} onClick={() => attempt(() => changePlan(importExpenseSuggestions(plan, library, suggestions, "HISTORICAL")))}>Build from historical spending</Button><Button variant="secondary" disabled={!suggestions.some(x => x.source_type === "RECURRING")} onClick={() => attempt(() => changePlan(importExpenseSuggestions(plan, library, suggestions, "RECURRING")))}>Import recurring commitments</Button><Button variant="secondary" onClick={() => attempt(() => { const copy = duplicateExpensePlan(plan, library); save({ ...library, plans: [...library.plans, copy] }); onSelectPlan(copy.id); })}>Duplicate Expense Plan</Button><Button variant="secondary" onClick={() => { if (window.confirm(`Delete expense plan “${plan.name}”? Plans used by saved scenarios cannot be deleted.`)) attempt(() => { save({ ...library, plans: library.plans.filter(p => p.id !== plan.id) }); onSelectPlan(""); }); }}>Delete Expense Plan</Button></div>
      <p className="text-xs text-slate-500">Imports are suggestions, not confirmations. Historical averages exclude the incomplete current month and linked recurring/instalment transactions. Reimporting a source will not duplicate or overwrite its planned item.</p>
      <div className="grid gap-2 sm:grid-cols-4"><label className="text-xs">Filter type<Select value={filters.type} onChange={e => setFilters({ ...filters, type: e.target.value, category: "" })}><option value="">All types</option>{ordered(library.types).map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</Select></label><label className="text-xs">Filter category<Select value={filters.category} onChange={e => setFilters({ ...filters, category: e.target.value })}><option value="">All categories</option>{ordered(library.categories.filter(c => !filters.type || c.type_id === filters.type)).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></label><label className="text-xs">Filter source<Select value={filters.source} onChange={e => setFilters({ ...filters, source: e.target.value })}><option value="">All sources</option>{["HISTORICAL", "RECURRING", "USER_CREATED", "USER_OVERRIDE"].map(x => <option key={x}>{x}</option>)}</Select></label><label className="text-xs">Filter enabled status<Select value={filters.enabled} onChange={e => setFilters({ ...filters, enabled: e.target.value })}><option value="all">All items</option><option value="enabled">Included</option><option value="disabled">Excluded / disabled</option></Select></label></div>
      <div className="space-y-5">{ordered(library.types).map(type => { const items = visible.filter(i => i.type_id === type.id && i.category_id); return items.length ? <section key={type.id}><h3 className="mb-2 font-semibold">{type.name} <span className="text-xs font-normal text-slate-500">{type.behavior_tag}{type.is_active ? "" : " · Disabled"}</span></h3>{ordered(library.categories.filter(c => c.type_id === type.id)).map(category => { const children = items.filter(i => i.category_id === category.id); return children.length ? <div key={category.id} className="mb-3 space-y-2 border-l-2 border-teal-200 pl-3 dark:border-teal-800"><h4 className="text-sm font-medium">{category.name}{category.is_active ? "" : " · Disabled"}</h4>{children.map(renderItem)}</div> : null; })}</section> : null; })}{visible.some(i => !i.type_id || !i.category_id) && <section className="space-y-2"><h3 className="font-semibold text-amber-700 dark:text-amber-300">Unmapped — choose a type and category</h3>{visible.filter(i => !i.type_id || !i.category_id).map(renderItem)}</section>}{!visible.length && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-800">No items match. Add an expense or import suggestions to build your living plan.</p>}</div>
      <details className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><summary className="cursor-pointer text-sm font-medium">Generate a Lean / Normal / Comfortable copy</summary><p className="mt-2 text-xs text-slate-500">Only REDUCIBLE and OPTIONAL items without a fixed-amount flag are scaled. MANDATORY and COMMITMENT items stay unchanged. Generated amounts become explicit editable items; no multiplier is applied during projection.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">New lifestyle plan name<Input placeholder="Lean Lifestyle" value={copyName} onChange={e => setCopyName(e.target.value)} /></label><label className="text-sm">Reducible / optional multiplier<Input type="number" min={0} max={5} step="0.05" value={factor} onChange={e => setFactor(Number(e.target.value))} /></label></div><Button className="mt-3" variant="secondary" onClick={() => attempt(() => { const copy = duplicateExpensePlan(plan, library, factor, copyName.trim() || `${plan.name} (${factor}x optional spending)`); save({ ...library, plans: [...library.plans, copy] }); onSelectPlan(copy.id); })}>Generate explicit plan copy</Button></details>
      {errors.length > 0 && <ul role="alert" className="list-inside list-disc text-sm text-amber-700 dark:text-amber-300">{errors.map(e => <li key={e}>{e}</li>)}</ul>}
      <div className="rounded-xl border border-teal-200 p-4 dark:border-teal-800"><p className="text-sm">{plan.items.filter(i => i.enabled && !itemIsEnabled(i, library)).length} enabled items are excluded by unmapped or disabled classifications. Review these before confirming.</p><Button className="mt-3" disabled={errors.length > 0 || summary.missingFx || plan.confirmed} onClick={() => attempt(() => changePlan({ ...plan, confirmed: true, updated_at: new Date().toISOString() }))}>{plan.confirmed ? "Expense plan confirmed" : "Confirm future expense plan"}</Button></div>
    </>}
    <FutureExpenseHierarchy library={library} onChange={save} />
  </div>;
}
