"use client";
import { useState } from "react";
import type { ExpenseBehavior, FutureExpenseLibrary } from "../types/futureExpense";
import { behaviors, deleteExpenseCategory, deleteExpenseType, moveExpenseCategory, newExpenseCategory, newExpenseType, ordered, starterExpenseStructure } from "../utils/futureExpense";
import { Button } from "./ui/Button";
import { Input, Select, Textarea } from "./ui/Field";

export default function FutureExpenseHierarchy({ library, onChange }: { library: FutureExpenseLibrary; onChange: (next: FutureExpenseLibrary) => void }) {
  const [deleting, setDeleting] = useState<{ kind: "type" | "category"; id: string } | null>(null);
  const [destination, setDestination] = useState("");
  const [error, setError] = useState("");
  const invalidate = (next: FutureExpenseLibrary, typeId?: string, categoryId?: string) => ({ ...next, plans: next.plans.map(p => ({ ...p, confirmed: p.items.some(i => i.type_id === typeId || i.category_id === categoryId) ? false : p.confirmed })) });
  const save = (next: FutureExpenseLibrary) => { try { onChange(next); setError(""); } catch (e) { setError((e as Error).message); } };
  function reorder(kind: "types" | "categories", id: string, direction: number) {
    const item = library[kind].find(x => x.id === id)!;
    const siblings = ordered(library[kind].filter(x => kind === "types" || ("type_id" in x && "type_id" in item && x.type_id === item.type_id)));
    const index = siblings.findIndex(x => x.id === id), target = siblings[index + direction];
    if (!target) return;
    [siblings[index], siblings[index + direction]] = [siblings[index + direction], siblings[index]];
    const positions = new Map(siblings.map((x, i) => [x.id, i]));
    save({ ...library, [kind]: library[kind].map(x => ({ ...x, sort_order: positions.get(x.id) ?? x.sort_order })) });
  }
  const childCategories = deleting?.kind === "type" ? library.categories.filter(c => c.type_id === deleting.id) : [];
  const childItems = deleting ? library.plans.flatMap(p => p.items).filter(i => deleting.kind === "type" ? i.type_id === deleting.id : i.category_id === deleting.id).length : 0;
  return <details className="rounded-xl border border-slate-200 p-4 dark:border-slate-700">
    <summary className="cursor-pointer font-semibold">Manage Types & Categories</summary>
    <p className="mt-3 text-sm text-slate-500">Shared across all future plans. Names are labels; behavior metadata controls cost treatment. Disabling a type or category excludes its items from projections and requires affected plans to be reviewed again.</p>
    {error && <p role="alert" className="my-3 text-sm text-amber-700">{error}</p>}
    <div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" onClick={() => save({ ...library, types: [...library.types, { ...newExpenseType(), sort_order: library.types.length }] })}>Add Type</Button>{!library.types.length && <Button variant="secondary" onClick={() => save(starterExpenseStructure(library))}>Use optional starter structure</Button>}</div>
    <div className="mt-4 space-y-4">{ordered(library.types).map((type, index) => <section key={type.id} aria-label={`Type ${type.name}`} className="space-y-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-800">
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Type name<Input value={type.name} onChange={e => save({ ...library, plans: e.target.value.trim() ? library.plans : invalidate(library, type.id).plans, types: library.types.map(t => t.id === type.id ? { ...t, name: e.target.value, updated_at: new Date().toISOString() } : t) })} /></label><label className="text-sm">Behavior<Select value={type.behavior_tag} onChange={e => save(invalidate({ ...library, types: library.types.map(t => t.id === type.id ? { ...t, behavior_tag: e.target.value as ExpenseBehavior, updated_at: new Date().toISOString() } : t) }, type.id))}>{behaviors.map(b => <option key={b}>{b}</option>)}</Select></label></div>
      <label className="block text-sm">Type description<Textarea value={type.description} onChange={e => save({ ...library, types: library.types.map(t => t.id === type.id ? { ...t, description: e.target.value } : t) })} /></label>
      <div className="flex flex-wrap items-center gap-2"><label className="mr-3 flex gap-2 text-sm"><input type="checkbox" checked={type.is_active} onChange={e => save(invalidate({ ...library, types: library.types.map(t => t.id === type.id ? { ...t, is_active: e.target.checked } : t) }, type.id))} />Type active</label><Button size="sm" variant="secondary" disabled={!index} onClick={() => reorder("types", type.id, -1)}>Move type up</Button><Button size="sm" variant="secondary" disabled={index === library.types.length - 1} onClick={() => reorder("types", type.id, 1)}>Move type down</Button><Button size="sm" variant="secondary" onClick={() => save({ ...library, categories: [...library.categories, { ...newExpenseCategory(type.id), sort_order: library.categories.filter(c => c.type_id === type.id).length }] })}>Add Category</Button><Button size="sm" variant="secondary" onClick={() => { setDeleting({ kind: "type", id: type.id }); setDestination(""); }}>Delete Type</Button></div>
      <div className="space-y-3 border-l-2 border-teal-200 pl-3 dark:border-teal-800">{ordered(library.categories.filter(c => c.type_id === type.id)).map((category, index, siblings) => <div key={category.id} aria-label={`Category ${category.name}`} className="space-y-2 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Category name<Input value={category.name} onChange={e => save({ ...library, plans: e.target.value.trim() ? library.plans : invalidate(library, undefined, category.id).plans, categories: library.categories.map(c => c.id === category.id ? { ...c, name: e.target.value, updated_at: new Date().toISOString() } : c) })} /></label><label className="text-sm">Parent type<Select value={category.type_id} onChange={e => save(moveExpenseCategory(library, category.id, e.target.value))}>{ordered(library.types).map(t => <option key={t.id} value={t.id}>{t.name || "Unnamed type"}</option>)}</Select></label></div><label className="block text-sm">Category description<Input value={category.description} onChange={e => save({ ...library, categories: library.categories.map(c => c.id === category.id ? { ...c, description: e.target.value } : c) })} /></label><div className="flex flex-wrap items-center gap-2"><label className="mr-2 flex gap-2 text-sm"><input type="checkbox" checked={category.is_active} onChange={e => save(invalidate({ ...library, categories: library.categories.map(c => c.id === category.id ? { ...c, is_active: e.target.checked } : c) }, undefined, category.id))} />Category active</label><Button size="sm" variant="secondary" disabled={!index} onClick={() => reorder("categories", category.id, -1)}>Move category up</Button><Button size="sm" variant="secondary" disabled={index === siblings.length - 1} onClick={() => reorder("categories", category.id, 1)}>Move category down</Button><Button size="sm" variant="secondary" onClick={() => { setDeleting({ kind: "category", id: category.id }); setDestination(""); }}>Delete Category</Button></div></div>)}</div>
    </section>)}</div>
    {deleting && <div role="dialog" aria-label="Safe deletion" className="mt-4 space-y-3 rounded-xl border-2 border-amber-300 bg-amber-50 p-4 text-slate-900"><p className="font-medium">This {deleting.kind} contains {deleting.kind === "type" ? `${childCategories.length} categories and ` : ""}{childItems} expense items.</p><p className="text-sm">Child records are preserved by reassignment. No cascade deletion is performed.</p><label className="block text-sm">Move children to<Select value={destination} onChange={e => setDestination(e.target.value)}><option value="">Choose destination</option>{(deleting.kind === "type" ? ordered(library.types) : ordered(library.categories)).filter(x => x.id !== deleting.id).map(x => <option key={x.id} value={x.id}>{"type_id" in x ? `${library.types.find(t => t.id === x.type_id)?.name} / ` : ""}{x.name}</option>)}</Select></label><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => { try { onChange(deleting.kind === "type" ? deleteExpenseType(library, deleting.id, destination || undefined) : deleteExpenseCategory(library, deleting.id, destination || undefined)); setDeleting(null); setError(""); } catch (e) { setError((e as Error).message); } }}>Reassign and delete {deleting.kind}</Button><Button variant="secondary" onClick={() => { const next = deleting.kind === "type" ? invalidate({ ...library, types: library.types.map(t => t.id === deleting.id ? { ...t, is_active: false } : t) }, deleting.id) : invalidate({ ...library, categories: library.categories.map(c => c.id === deleting.id ? { ...c, is_active: false } : c) }, undefined, deleting.id); save(next); setDeleting(null); }}>Disable instead</Button><Button variant="secondary" onClick={() => setDeleting(null)}>Cancel deletion</Button></div></div>}
  </details>;
}
