"use client";
import { useState, type ReactNode } from "react";
import { Button } from "./ui/Button";
import { Input, Select, Textarea } from "./ui/Field";
import type { Assumption, LifeScenario, ScenarioEvent, ScenarioIncome } from "../types/lifeScenario";
import { addMonths, assumption, convert, makePhase, nextDay, uid } from "../utils/lifeScenario";
import FutureExpensePlanEditor from "./FutureExpensePlanEditor";
import type { FutureExpenseLibrary } from "../types/futureExpense";
import { applyTransition, employmentVariants, type JobTransition } from "../utils/scenarioTransition";

export function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block min-w-0 space-y-1 text-sm"><span className="text-slate-500 dark:text-slate-400">{label}</span>{children}</label>; }
export function NumberField({ label, value, onChange, min }: { label: string; value: number; onChange: (n: number) => void; min?: number }) { return <Field label={label}><Input type="number" step="any" min={min} value={Number.isFinite(value) ? value : ""} onChange={e => onChange(e.target.value === "" ? 0 : Number(e.target.value))} /></Field>; }
export function MoneyEditor({ label, value, onChange, base, scenario }: { label: string; value: Assumption; onChange: (a: Assumption) => void; base: string; scenario: LifeScenario }) {
  return <div className="space-y-1"><div className="grid grid-cols-[1fr_90px] gap-2"><NumberField label={label} value={value.amount} onChange={amount => onChange({ ...value, amount, source_type: "USER_OVERRIDE" })} /><Field label="Currency"><Select value={value.currency} onChange={e => onChange({ ...value, currency: e.target.value as Assumption["currency"], source_type: "USER_OVERRIDE" })}><option>MYR</option><option>SGD</option></Select></Field></div><p className="text-xs text-slate-500">{value.source_type.replaceAll("_", " ")} {value.currency !== base && (scenario.fx[value.currency] > 0 ? ` · ${convert(value, scenario).toFixed(2)} ${base} at ${scenario.fx[value.currency]}` : " · Set an FX assumption")}</p></div>;
}

const templates = ["Current Job", "Unemployed", "Career Break", "Travel", "Job Search", "New Job", "Relocation", "Custom"];

export default function LifeScenarioEditor({ scenario: s, onChange, onVariants, library, onLibraryChange, usage }: { scenario: LifeScenario; onChange: (s: LifeScenario) => void; onVariants: (s: LifeScenario[]) => void; library: FutureExpenseLibrary; onLibraryChange: (library: FutureExpenseLibrary) => void; usage: Record<string, number> }) {
  const [template, setTemplate] = useState("Career Break");
  const [workflow, setWorkflow] = useState(false);
  const [workflowError, setWorkflowError] = useState("");
  const [transition, setTransition] = useState<JobTransition>(() => ({ last_working_day: nextDay(addMonths(s.start_date.slice(0, 7) + "-01", 1), -1), final_salary_date: nextDay(addMonths(s.start_date.slice(0, 7) + "-01", 1), -1), final_salary: s.baseline.income.amount, new_job_start: "", first_salary_date: "", new_salary: 0, relocation_cost: 0, travel_cost: 0, new_rent: null, new_transport: null }));
  const update = (patch: Partial<LifeScenario>) => onChange({ ...s, ...patch });
  const baseline = (patch: Partial<LifeScenario["baseline"]>) => update({ baseline: { ...s.baseline, ...patch, reviewed: false } });
  const money = (label: string, value: Assumption, onChange: (a: Assumption) => void) => <MoneyEditor label={label} value={value} onChange={onChange} base={s.currency} scenario={s} />;
  return <div className="space-y-6">
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Scenario name"><Input value={s.name} onChange={e => update({ name: e.target.value })} /></Field><Field label="Status"><Select value={s.status} onChange={e => update({ status: e.target.value as LifeScenario["status"] })}>{["DRAFT", "ACTIVE", "ARCHIVED"].map(x => <option key={x}>{x}</option>)}</Select></Field><Field label="Projection starts"><Input type="date" min={s.baseline.as_of} value={s.start_date} onChange={e => update({ start_date: e.target.value })} /></Field><Field label="Projection ends"><Input type="date" value={s.projection_end_date} onChange={e => update({ projection_end_date: e.target.value })} /></Field></div>
    <Field label="What changes in your life?"><Textarea value={s.description} onChange={e => update({ description: e.target.value })} /></Field>
    <NumberField label={`Minimum safety reserve (${s.currency}) · User Override`} min={0} value={s.minimum_reserve} onChange={minimum_reserve => update({ minimum_reserve })} />
    <details open className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">1. Select liquid assets and review current income</summary><div className="mt-4 space-y-4">
      <p className="text-sm text-slate-500">{s.baseline.completed_months.length ? `${s.baseline.completed_months.length} completed months (${s.baseline.completed_months[0]} to ${s.baseline.completed_months.at(-1)}).` : "No completed history: enter your own assumptions."} The incomplete current month is excluded. Spending history is reference only; it is not a future living budget. Linked recurring and instalment transactions are excluded from lifestyle averages to avoid double counting.</p>
      <p className="text-sm">Assets as of {s.baseline.as_of}. Select only liquid assets available for this plan, or enter a total below.</p>
      <div className="grid gap-2 sm:grid-cols-2">{s.baseline.asset_candidates.map(a => <label key={a.id} className="flex items-center gap-2 rounded-lg bg-slate-100 p-3 dark:bg-slate-800"><input type="checkbox" checked={a.included} onChange={e => { const candidates = s.baseline.asset_candidates.map(x => x.id === a.id ? { ...x, included: e.target.checked } : x); baseline({ asset_candidates: candidates, liquid_assets: assumption(candidates.filter(x => x.included).reduce((sum, x) => sum + x.amount, 0), s.currency) }); }} />{a.name} · {a.amount.toFixed(2)} {s.currency}</label>)}</div>
      <div className="grid gap-4 sm:grid-cols-2">{money("Starting liquid assets", s.baseline.liquid_assets, liquid_assets => baseline({ liquid_assets, asset_candidates: s.baseline.asset_candidates.map(a => ({ ...a, included: false })) }))}{money("Monthly income", s.baseline.income, income => baseline({ income }))}{money("Current monthly savings pace", s.baseline.savings_pace, savings_pace => baseline({ savings_pace }))}</div>
      <p className="text-xs text-slate-500">Starting assets are the balance available at projection start. For a future start, enter your expected balance. Ready date uses the confirmed baseline savings pace; it does not shift dated commitments or promise future income.</p>
      {s.start_date.slice(0, 7) === s.baseline.as_of.slice(0, 7) && <p className="rounded-lg bg-sky-50 p-3 text-sm text-sky-900 dark:bg-sky-950 dark:text-sky-100">Recorded this month through {s.baseline.as_of}: income {s.baseline.actual_current_income.toFixed(2)}, spending {s.baseline.actual_current_expenses.toFixed(2)} {s.currency}. These are already reflected in current assets and are not applied again. Review the remaining cashflows from the start date, including any payments already made today.</p>}
    </div></details>
    <details open className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">2. Define future monthly living expenses</summary><div className="mt-4"><FutureExpensePlanEditor library={library} onChange={onLibraryChange} currency={s.currency} fx={s.fx} suggestions={s.baseline.expenses} selectedPlanId={s.expense_plan_id} onSelectPlan={expense_plan_id => update({ expense_plan_id })} usage={usage} /></div></details>
    <details open className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">3. Confirm temporary commitments</summary><div className="mt-4 space-y-4">
      <details><summary className="cursor-pointer text-sm font-medium">Existing commitments · {s.baseline.repayments.reduce((sum, p) => sum + p.amount, 0).toFixed(2)} {s.currency} outstanding</summary><ul className="mt-2 max-h-60 overflow-y-auto text-sm">{s.baseline.repayments.map(p => <li key={p.id} className="flex justify-between gap-3 border-b border-slate-100 py-2 dark:border-slate-800"><span>{p.name} · {p.date}</span><span>{p.amount.toFixed(2)} {p.currency} · Existing Commitment</span></li>)}</ul><p className="text-xs text-slate-500">Only scheduled repayments are imported. Overdue scheduled payments are placed on the baseline date. Payments stop at their final scheduled date.</p></details>
      <details><summary className="cursor-pointer text-sm font-medium">Adjust hypothetical repayment assumptions</summary><p className="mt-2 text-xs text-slate-500">Imported schedules stay separate from your actual payment plans. Add missing repayments or change dates and amounts only for this scenario.</p><div className="mt-3 max-h-96 space-y-3 overflow-y-auto">{s.baseline.repayments.map(p => <div key={p.id} className="grid gap-2 rounded-lg bg-slate-50 p-3 dark:bg-slate-800 sm:grid-cols-2"><Field label="Repayment name"><Input value={p.name} onChange={e => baseline({ repayments: s.baseline.repayments.map(x => x.id === p.id ? { ...x, name: e.target.value } : x) })} /></Field><Field label="Repayment date"><Input type="date" value={p.date} onChange={e => baseline({ repayments: s.baseline.repayments.map(x => x.id === p.id ? { ...x, date: e.target.value, source_type: "USER_OVERRIDE" } : x) })} /></Field>{money("Repayment amount", p, a => baseline({ repayments: s.baseline.repayments.map(x => x.id === p.id ? { ...x, ...a } : x) }))}<Button variant="secondary" onClick={() => baseline({ repayments: s.baseline.repayments.filter(x => x.id !== p.id) })}>Remove hypothetical repayment</Button></div>)}</div><Button className="mt-3" variant="secondary" onClick={() => baseline({ repayments: [...s.baseline.repayments, { ...assumption(0, s.currency), id: uid(), name: "Repayment", date: s.start_date }] })}>Add dated repayment</Button></details>
      <label className="flex items-center gap-3 rounded-xl bg-teal-50 p-4 dark:bg-teal-950"><input type="checkbox" checked={s.baseline.reviewed} onChange={e => update({ baseline: { ...s.baseline, reviewed: e.target.checked } })} />I have reviewed liquid assets, temporary commitments and remaining-month assumptions.</label>
    </div></details>
    <details open className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">4. Define life phases and future income</summary><div className="mt-4 space-y-4">
      <p className="text-sm text-slate-500">Uncovered dates use the selected scenario expense plan and baseline income. Every phase selects its own expense plan; overrides change only that phase. Monthly amounts are prorated by calendar day; dated salaries and recurring commitments are paid on their payment date.</p>
      <Button variant="secondary" onClick={() => setWorkflow(!workflow)}>Plan Leaving My Job / Job Transition</Button>
      {workflow && <div className="space-y-4 rounded-xl bg-slate-100 p-4 dark:bg-slate-800"><h3 className="font-semibold">Job transition setup</h3><p className="text-sm">Confirm assets and commitments above, then define the unpaid gap and next job if known. This replaces phases and prior workflow events; your custom one-time events are kept. Review the career-break lifestyle afterward.</p><div className="grid gap-3 sm:grid-cols-2">
        {([['last_working_day', 'Last working day'], ['final_salary_date', 'Final salary date'], ['new_job_start', 'New job start (blank = unknown)'], ['first_salary_date', 'Expected first salary date']] as const).map(([key, label]) => <Field label={label} key={key}><Input type="date" value={transition[key]} onChange={e => setTransition({ ...transition, [key]: e.target.value })} /></Field>)}
        {([['final_salary', 'Final salary amount'], ['new_salary', 'Expected new monthly salary'], ['travel_cost', 'Planned travel cost'], ['relocation_cost', 'Relocation cost']] as const).map(([key, label]) => <NumberField key={key} label={`${label} (${s.currency})`} value={transition[key]} onChange={n => setTransition({ ...transition, [key]: n })} />)}
        {([['new_rent', 'New rent (blank = inherit)'], ['new_transport', 'New transport (blank = inherit)']] as const).map(([key, label]) => <Field label={label} key={key}><Input type="number" min={0} value={transition[key] ?? ""} onChange={e => setTransition({ ...transition, [key]: e.target.value === "" ? null : Number(e.target.value) })} /></Field>)}
      </div><div className="grid gap-3 sm:grid-cols-2">{([["rent_item_id", "Rent expense item"], ["transport_item_id", "Transport expense item"]] as const).map(([key, label]) => <Field key={key} label={label}><Select value={transition[key] || ""} onChange={e => setTransition({ ...transition, [key]: e.target.value })}><option value="">Select plan item to override (optional)</option>{(library.plans.find(p => p.id === s.expense_plan_id)?.items || []).map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</Select></Field>)}</div><p className="text-xs text-slate-500">Salary amounts are user assumptions in {s.currency}. No next salary is assumed when the job date is unknown. Comparison variants assume first salary is received on the proposed start date; edit it if delayed.</p>{workflowError && <p role="alert">{workflowError}</p>}<div className="flex flex-wrap gap-2"><Button onClick={() => { try { onChange(applyTransition(s, transition, library)); setWorkflowError(""); setWorkflow(false); } catch (e) { setWorkflowError((e as Error).message); } }}>Generate phases</Button><Button variant="secondary" onClick={() => { try { onVariants(employmentVariants(s, transition, library)); setWorkflowError(""); } catch (e) { setWorkflowError((e as Error).message); } }}>Compare jobs after 3 / 6 / 12 months</Button></div></div>}
      {s.phases.map(p => {
        const edit = (patch: Partial<typeof p>) => update({ phases: s.phases.map(x => x.id === p.id ? { ...x, ...patch, updated_at: new Date().toISOString() } : x) });
        return <div key={p.id} className="space-y-3 rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="grid gap-3 sm:grid-cols-2"><Field label="Phase name"><Input value={p.name} onChange={e => edit({ name: e.target.value })} /></Field><Field label="Location"><Input value={p.location_label} onChange={e => edit({ location_label: e.target.value })} /></Field><Field label="From"><Input type="date" value={p.start_date} onChange={e => edit({ start_date: e.target.value })} /></Field><Field label="Through"><Input type="date" value={p.end_date} onChange={e => edit({ end_date: e.target.value })} /></Field></div>
          <Field label="Phase expense plan"><Select value={p.expense_plan_id} onChange={e => edit({ expense_plan_id: e.target.value, expense_overrides: {} })}><option value="">Choose a future living plan</option>{library.plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name} ? {plan.confirmed ? "Confirmed" : "Draft"}</option>)}</Select></Field>
          <Field label="Income during this phase"><Select value={p.incomes === null ? "baseline" : p.incomes.length ? "custom" : "none"} onChange={e => edit({ incomes: e.target.value === "baseline" ? null : e.target.value === "none" ? [] : [{ ...assumption(0, s.currency), id: uid(), kind: "salary" }] })}><option value="baseline">Use baseline income</option><option value="none">No income</option><option value="custom">Custom income</option></Select></Field>
          {p.incomes?.map(income => { const change = (patch: Partial<ScenarioIncome>) => edit({ incomes: p.incomes!.map(i => i.id === income.id ? { ...i, ...patch } : i) }); return <div className="grid items-end gap-3 sm:grid-cols-2" key={income.id}>{money("Monthly income", income, change)}<Field label="Income kind"><Select value={income.kind} onChange={e => change({ kind: e.target.value as ScenarioIncome["kind"] })}>{["salary", "freelance", "part-time", "benefits", "bonus", "other"].map(k => <option key={k}>{k}</option>)}</Select></Field><Field label="First payment date (optional)"><Input type="date" value={income.first_payment_date || ""} onChange={e => change({ first_payment_date: e.target.value || undefined })} /></Field><Field label="Payment day (blank = daily proration)"><Input type="number" min={1} max={31} value={income.payment_day ?? ""} onChange={e => change({ payment_day: e.target.value ? Number(e.target.value) : undefined })} /></Field><Button variant="secondary" onClick={() => edit({ incomes: p.incomes!.filter(i => i.id !== income.id) })}>Remove income</Button></div>; })}
          {p.incomes !== null && <Button variant="secondary" onClick={() => edit({ incomes: [...p.incomes!, { ...assumption(0, s.currency), id: uid(), kind: "other" }] })}>Add income stream</Button>}
          <details><summary className="cursor-pointer text-sm font-medium">Change this phase’s expenses ({Object.keys(p.expense_overrides).length} overrides)</summary><div className="mt-3 space-y-3">{(library.plans.find(plan => plan.id === p.expense_plan_id)?.items || []).map(x => { const override = p.expense_overrides[x.id]; return <div key={x.id} className="space-y-2 rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><label className="flex gap-2 text-sm"><input type="checkbox" checked={!!override} onChange={e => { const overrides = { ...p.expense_overrides }; if (e.target.checked) overrides[x.id] = { ...assumption(x.amount, x.currency), enabled: x.enabled }; else delete overrides[x.id]; edit({ expense_overrides: overrides }); }} />Override {x.name} · baseline {x.amount.toFixed(2)} {x.currency}</label>{override && <div className="flex items-end gap-3">{money(x.name, override, a => edit({ expense_overrides: { ...p.expense_overrides, [x.id]: { ...override, ...a } } }))}<label className="flex gap-2 py-3"><input type="checkbox" checked={override.enabled} onChange={e => edit({ expense_overrides: { ...p.expense_overrides, [x.id]: { ...override, enabled: e.target.checked } } })} />Keep</label></div>}</div>; })}</div></details>
          <Field label="Phase notes"><Textarea value={p.note} onChange={e => edit({ note: e.target.value })} /></Field><Button variant="secondary" onClick={() => update({ phases: s.phases.filter(x => x.id !== p.id), events: s.events.map(e => e.phase_id === p.id ? { ...e, phase_id: undefined } : e) })}>Remove phase</Button>
        </div>;
      })}
      <div className="flex flex-wrap gap-2"><Select aria-label="Phase template" value={template} onChange={e => setTemplate(e.target.value)} className="max-w-60">{templates.map(t => <option key={t}>{t}</option>)}</Select><Button variant="secondary" onClick={() => { const previous = [...s.phases].sort((a, b) => a.end_date.localeCompare(b.end_date)).at(-1); const start = previous ? nextDay(previous.end_date) : s.start_date; const end = nextDay(addMonths(start, 1), -1); update({ phases: [...s.phases, makePhase(s, template, start, end)], projection_end_date: end > s.projection_end_date ? end : s.projection_end_date }); }}>Add phase</Button></div>
    </div></details>
    <details className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">5. One-time events ({s.events.length})</summary><div className="mt-4 space-y-4">{s.events.map(e => { const edit = (patch: Partial<ScenarioEvent>) => update({ events: s.events.map(x => x.id === e.id ? { ...x, ...patch } : x) }); return <div key={e.id} className="grid gap-3 rounded-lg bg-slate-50 p-3 dark:bg-slate-800 sm:grid-cols-2"><Field label="Description"><Input value={e.description} onChange={x => edit({ description: x.target.value })} /></Field><Field label="Date"><Input type="date" value={e.date} onChange={x => edit({ date: x.target.value })} /></Field>{money("Amount", e, edit)}<Field label="Event type"><Select value={e.type} onChange={x => { const type = x.target.value as ScenarioEvent["type"]; edit({ type, direction: ["ONE_TIME_INCOME", "BONUS", "REFUND"].includes(type) ? "income" : "expense" }); }}>{["ONE_TIME_INCOME", "ONE_TIME_EXPENSE", "RELOCATION_COST", "TRAVEL_COST", "DEPOSIT", "BONUS", "REFUND", "OTHER"].map(t => <option key={t}>{t}</option>)}</Select></Field><Field label="Direction"><Select value={e.direction} onChange={x => edit({ direction: x.target.value as ScenarioEvent["direction"] })}><option value="income">Money in</option><option value="expense">Money out</option></Select></Field><Field label="Linked phase (optional)"><Select value={e.phase_id || ""} onChange={x => edit({ phase_id: x.target.value || undefined })}><option value="">None</option>{s.phases.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><Button variant="secondary" onClick={() => update({ events: s.events.filter(x => x.id !== e.id) })}>Remove event</Button></div>; })}<Button variant="secondary" onClick={() => update({ events: [...s.events, { ...assumption(0, s.currency), id: uid(), scenario_id: s.id, date: s.start_date, type: "ONE_TIME_EXPENSE", direction: "expense", description: "One-time cost" }] })}>Add one-time event</Button></div></details>
    <details className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">Advanced: inflation, expected yield & FX</summary><div className="mt-4 space-y-4">      <label className="flex gap-2"><input type="checkbox" checked={s.inflation_enabled} onChange={e => update({ inflation_enabled: e.target.checked })} />Enable inflation</label>{s.inflation_enabled && <NumberField label="Annual inflation % · User Override" value={s.inflation_rate} onChange={inflation_rate => update({ inflation_rate })} />}<p className="text-xs text-slate-500">Monthly compounding applies to lifestyle expenses. Fixed recurring payments, instalments and one-time events are excluded.</p>
      <label className="flex gap-2"><input type="checkbox" checked={s.yield_enabled} onChange={e => update({ yield_enabled: e.target.checked })} />Enable expected cash / MMF yield</label>{s.yield_enabled && <div className="grid gap-4 sm:grid-cols-2"><NumberField label="Expected annual yield % · User Override" value={s.yield_rate} onChange={yield_rate => update({ yield_rate })} /><NumberField label={`Eligible balance cap (${s.currency}) · User Override`} value={s.yield_eligible_balance} onChange={yield_eligible_balance => update({ yield_eligible_balance })} /></div>}<p className="text-xs text-slate-500">Expected yield is not guaranteed. It applies to the smaller of positive opening cash and your eligible balance cap, with partial-month compounding.</p>
      <NumberField label={`1 ${s.currency === "MYR" ? "SGD" : "MYR"} = how many ${s.currency}? · User Override`} value={s.fx[s.currency === "MYR" ? "SGD" : "MYR"]} onChange={n => update({ fx: { ...s.fx, [s.currency === "MYR" ? "SGD" : "MYR"]: n } })} /><p className="text-xs text-slate-500">FX is a scenario assumption, not a guaranteed rate. Original amounts and currencies are retained. Base currency is fixed at creation.</p>
    </div></details>
  </div>;
}
