"use client";
import { useMemo } from "react";
import { CartesianGrid, Line, LineChart, ReferenceDot, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card } from "./ui/Card";
import FutureExpenseAnalysis from "./FutureExpenseAnalysis";
import type { FutureExpenseLibrary } from "../types/futureExpense";
import type { LifeScenario, ProjectionMonth } from "../types/lifeScenario";
import { analyzeScenario, convert, runwayScenario } from "../utils/lifeScenario";
import { latestAffordableStart } from "../utils/scenarioTransition";

export function money(n: number, currency: string) { return new Intl.NumberFormat("en-MY", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number.isFinite(n) ? n : 0); }
function Metric({ label, value, note }: { label: string; value: string; note?: string }) { return <div className="min-w-0 rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p className="text-xs text-slate-500 dark:text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold tracking-tight">{value}</p>{note && <p className="mt-1 text-xs text-slate-500">{note}</p>}</div>; }
export default function LifeScenarioResults({ scenario: s, goalTarget, library }: { scenario: LifeScenario; goalTarget?: number; library: FutureExpenseLibrary }) {
  const result = useMemo(() => analyzeScenario(s, library), [s, library]);
  const latest = useMemo(() => latestAffordableStart(s, library), [s, library]);
  const runway = useMemo(() => analyzeScenario(runwayScenario(s), library), [s, library]);
  if (!result) return null;
  const f = (n: number) => money(n, s.currency);
  const data = [...s.baseline.historical_assets.filter(x => x.month < s.start_date.slice(0, 7)).map(x => ({ month: x.month, actual: x.amount, projected: undefined as number | undefined })), { month: `${s.start_date} start`, actual: undefined as number | undefined, projected: result.starting }, ...result.rows.map(x => ({ month: x.month, actual: undefined as number | undefined, projected: x.closing_balance }))];
  const inputs = [s.baseline.income, ...library.plans.filter(p => p.id === s.expense_plan_id || s.phases.some(phase => phase.expense_plan_id === p.id)).flatMap(p => p.items.filter(x => x.enabled)), ...s.baseline.repayments, ...s.events, ...s.phases.flatMap(p => [...(p.incomes || []), ...Object.values(p.expense_overrides)])];
  const uncertain = inputs.filter(x => ["ESTIMATED", "HISTORICAL"].includes(x.source_type)).length;
  const quality = !inputs.length || !s.baseline.reviewed || uncertain > inputs.length / 2 ? "Limited" : uncertain ? "Moderate" : "Strong";
  const columns: [keyof ProjectionMonth, string][] = [["opening_balance", "Opening"], ["income", "Income"], ["essential_expenses", "Mandatory"], ["flexible_expenses", "Reducible"], ["discretionary_expenses", "Optional"], ["liability_payments", "Liabilities"], ["recurring_commitments", "Commitments"], ["one_time_events", "One-time costs"], ["one_time_income", "One-time income (included)"], ["investment_or_cash_yield", "Expected yield"], ["inflation_effect", "Inflation (included)"], ["total_outflow", "Total spending"], ["net_cashflow", "Net cashflow"], ["closing_balance", "Closing"]];
  return <div className="space-y-5">
    <FutureExpenseAnalysis scenario={s} library={library} result={result} />
    <Card><p className="text-sm font-medium text-teal-700 dark:text-teal-300">{result.buffer >= 0 ? "Above Reserve" : "Below Reserve"}</p><h2 className="mt-1 text-2xl font-semibold">{s.name}</h2><p className="mt-2 text-sm text-slate-500">{result.buffer >= 0 ? "Your entered plan stays above your reserve at the start and at each projected month end." : "Your entered plan falls below your reserve. Explore different dates, costs or starting funds."}</p><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-3">
      <Metric label="Required starting fund" value={f(result.required)} /><Metric label="Starting liquid assets" value={f(result.starting)} /><Metric label={result.gap ? "Funding gap" : "Funding surplus"} value={f(result.gap || result.surplus)} /><Metric label="Lowest projected balance" value={f(result.lowest)} note={result.lowestDate} /><Metric label="Estimated financially ready" value={result.readyDate || "Not calculated"} note={result.readyDate ? `At ${f(result.pace)} / month` : "Requires positive saving pace within 100 years"} /><Metric label="Safety buffer" value={f(result.buffer)} note={`Reserve ${f(result.reserve)}`} /><Metric label="Ending balance" value={f(result.ending)} note={s.projection_end_date} /><Metric label="Projection length" value={`${result.rows.length} months`} /><Metric label="Months without income" value={String(result.monthsWithoutIncome)} />
    </div></Card>
    <Card><h2 className="font-semibold">Life timeline</h2><div className="mt-4 flex gap-3 overflow-x-auto pb-2">{[...s.phases.map(p => ({ date: p.start_date, id: p.id, title: p.name, detail: `${p.start_date} → ${p.end_date}`, amount: `${f(p.incomes === null ? convert(s.baseline.income, s) : p.incomes.reduce((sum, i) => sum + convert(i, s), 0))} / month`, location: p.location_label })), ...s.events.map(e => ({ date: e.date, id: e.id, title: e.description, detail: e.date, amount: `${e.direction === "income" ? "+" : "−"}${f(convert(e, s))}`, location: "One-time event" }))].sort((a, b) => a.date.localeCompare(b.date)).map(p => <div key={p.id} className="min-w-52 rounded-xl border-l-4 border-teal-500 bg-slate-50 p-4 dark:bg-slate-800"><p className="text-xs text-slate-500">{p.detail}</p><p className="mt-2 font-medium">{p.title}</p><p className="text-sm">{p.amount}</p><p className="text-xs text-slate-500">{p.location}</p></div>)}{!s.phases.length && !s.events.length && <p className="text-sm text-slate-500">Baseline assumptions continue through the projection. Add phases to describe what changes.</p>}</div></Card>
    <Card><h2 className="font-semibold">Liquid asset projection</h2><p className="mt-1 text-xs text-slate-500">Dashed: projected month-end balances · Solid: selected historical snapshot scope · Reserve and zero shown. Intramonth cash timing can produce a lower balance.</p><div className="mt-4 h-80 w-full min-w-0"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 15, right: 25, left: 10, bottom: 10 }}><CartesianGrid strokeDasharray="3 3" opacity={0.2} /><XAxis dataKey="month" minTickGap={35} tick={{ fontSize: 11 }} /><YAxis tickFormatter={n => `${Math.round(Number(n) / 1000)}k`} tick={{ fontSize: 11 }} domain={["auto", "auto"]} /><Tooltip formatter={v => f(Number(v))} /><ReferenceLine ifOverflow="extendDomain" y={0} stroke="#94a3b8" /><ReferenceLine ifOverflow="extendDomain" y={s.minimum_reserve} stroke="#d97706" strokeDasharray="4 4" label="Reserve" />{goalTarget !== undefined && <ReferenceLine ifOverflow="extendDomain" y={goalTarget} stroke="#8b5cf6" strokeDasharray="4 4" label="Savings goal" />}<Line isAnimationActive={false} type="linear" dataKey="actual" name="ACTUAL" stroke="#64748b" strokeWidth={2} dot={false} /><Line isAnimationActive={false} type="linear" dataKey="projected" name="PROJECTED" stroke="#0d9488" strokeWidth={2} strokeDasharray="6 4" dot={false} /><ReferenceDot x={result.lowestDate === s.start_date ? `${s.start_date} start` : result.lowestDate} y={result.lowest} r={5} fill="#0d9488" stroke="white" /></LineChart></ResponsiveContainer></div>{!s.baseline.historical_assets.length && <p className="text-xs text-slate-500">No matching asset snapshots selected. Historical asset values are not reconstructed from spending.</p>}</Card>
    <Card><details><summary className="cursor-pointer font-semibold">More analysis & financial runway</summary><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-3"><Metric label="Total income" value={f(result.totalIncome)} /><Metric label="Total spending" value={f(result.totalSpending)} /><Metric label="Total liability payments" value={f(result.totalLiabilities)} /><Metric label="Total one-time costs" value={f(result.totalOneTime)} /><Metric label="First month at / below zero" value={result.firstZero || "Not within projection"} /><Metric label="Latest affordable new job start" value={latest || "No feasible date / no target job"} note="Within this horizon; generated New Job and preceding gap required" /><Metric label="No-income runway: below reserve" value={result.starting < s.minimum_reserve ? "At start" : runway?.firstBelowReserve || "Not within projection"} /><Metric label="No-income runway: at / below zero" value={result.starting <= 0 ? "At start" : runway?.firstZero || "Not within projection"} /></div><p className="mt-3 text-xs text-slate-500">Runway uses the same projection engine with the selected scenario living plan and all income removed. Scenario costs, commitments, reserve, inflation and yield are retained. Latest job start tests monthly delays across the same horizon; it does not predict when work will be found.</p></details></Card>
    <Card><details><summary className="cursor-pointer font-semibold">Assumptions · {quality} quality</summary><p className="mt-3 text-sm text-slate-500">Quality describes the sources you supplied, not the probability that the plan will happen. User-entered values are not independently verified.</p><ul className="mt-3 space-y-2 text-sm">{inputs.map((a, i) => <li key={i} className="flex flex-wrap justify-between gap-2 border-b border-slate-100 pb-2 dark:border-slate-800"><span>{"name" in a ? String(a.name) : "description" in a ? String(a.description) : "kind" in a ? String(a.kind) : "Baseline income"}{"date" in a ? ` · ${a.date}` : ""}</span><span>{a.amount.toFixed(2)} {a.currency} · {a.source_type.replaceAll("_", " ")}{a.currency !== s.currency ? ` → ${f(convert(a, s))}` : ""}</span></li>)}</ul><p className="mt-3 text-sm">Inflation: {s.inflation_enabled ? `${s.inflation_rate}%` : "Off"} · Expected yield: {s.yield_enabled ? `${s.yield_rate}% on up to ${f(s.yield_eligible_balance)}` : "Off"} · Lifestyle: {s.lifestyle} ({s.lifestyle === "NORMAL" ? 1 : s.flexible_multiplier}× flexible / discretionary) · User Override</p></details></Card>
    <Card><details><summary className="cursor-pointer font-semibold">Month-by-month details</summary><div className="mt-4 overflow-x-auto"><table className="w-full whitespace-nowrap text-right text-xs"><caption className="mb-2 text-left text-slate-500">All months PROJECTED in {s.currency}. Inflation is included in expense totals; one-time income is included in income.</caption><thead><tr><th className="p-2 text-left">Month</th>{columns.map(([key, title]) => <th className="p-2" key={key}>{title}</th>)}</tr></thead><tbody>{result.rows.map(r => <tr key={r.month} className="border-t border-slate-200 dark:border-slate-700"><th className="p-2 text-left">{r.month}</th>{columns.map(([key]) => <td className="p-2 tabular-nums" key={key}>{Number(r[key]).toFixed(2)}</td>)}</tr>)}</tbody></table></div></details></Card>
  </div>;
}

export function ScenarioComparison({ scenarios, library }: { scenarios: LifeScenario[]; library: FutureExpenseLibrary }) {
  const results = useMemo(() => scenarios.map(s => ({ s, r: analyzeScenario(s, library) })).filter(x => x.r), [scenarios, library]);
  if (results.length < 2) return null;
  const rows = [["Starting assets", "starting"], ["Lowest balance", "lowest"], ["Ending balance", "ending"], ["Required starting fund", "required"], ["Funding gap", "gap"], ["Safety buffer", "buffer"]] as const;
  return <Card><h2 className="font-semibold">Compare financial consequences</h2><p className="mt-1 text-sm text-slate-500">Each column retains its own dates and assumptions. No scenario is ranked.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[500px] text-left text-sm"><thead><tr><th className="p-3">Metric</th>{results.map(({ s }) => <th key={s.id} className="p-3">{s.name}<span className="block text-xs font-normal text-slate-500">{s.start_date} → {s.projection_end_date}</span></th>)}</tr></thead><tbody>{rows.map(([label, key]) => <tr key={key} className="border-t border-slate-200 dark:border-slate-700"><th className="p-3 font-normal">{label}</th>{results.map(({ s, r }) => <td key={s.id} className="p-3">{money(r![key], s.currency)}</td>)}</tr>)}<tr><th className="p-3 font-normal">Average monthly cashflow</th>{results.map(({ s, r }) => <td key={s.id} className="p-3">{money((r!.ending - r!.starting) / r!.rows.length, s.currency)} (varies)</td>)}</tr><tr><th className="p-3 font-normal">Estimated ready</th>{results.map(({ s, r }) => <td key={s.id} className="p-3">{r!.readyDate || "Not calculated"}</td>)}</tr></tbody></table></div></Card>;
}
